language: python
python:
  - "3.8.1"

      
# install dependencies
install:
  - pip install -r requirements.txt


notifications:
  email: false

# run pytest
script:
  - pytest --cov=app tests

# then post the results to coveralls
after_success:
  - coveralls